version: "3"
services:
  postgres:
    image: "postgres:9.5"
    environment:
      POSTGRES_PASSWORD: grafana
      POSTGRES_USER: grafana
      TZ: 'America/Sao_Paulo'
    ports:
    - 5432:5432
  influxdb:
    image: influxdb:alpine
    ports:
      - '8086:8086'
    #volumes:
    #  - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=influx
      - INFLUXDB_ADMIN_PASSWORD=influx
      - TZ='America/Sao_Paulo'
  grafana:
    image: "grafana/grafana:5.1.1"
    ports:
    - '3000:3000'
    hostname: grafana
    environment:
      GF_DATABASE_HOST: "postgres:5432"
      GF_DATABASE_PASSWORD: grafana
      GF_DATABASE_SSL_MODE: disable
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_USER: grafana
      GF_SECURITY_ADMIN_PASSWORD: SuperSecret
      GF_SECURITY_SECRET_KEY: "a4805ab98f842e901cd813b889fa3fc5107c9d75"
      GF_SERVER_DOMAIN: fiap.com.br
      GF_SERVER_ROOT_URL: https://localhost:3000/
      #GF_SESSION_PROVIDER: redis
      #GF_SESSION_PROVIDER_CONFIG: addr=redis:6379,pool_size=100,db=grafana
      #GF_USERS_ALLOW_ORG_CREATE: 'false'
      #GF_USERS_ALLOW_SIGN_UP: 'false'
      #GF_USERS_AUTO_ASSIGN_ORG: 'true'
      #GF_USERS_AUTO_ASSIGN_ORG_ROLE: Editor
      TZ: 'America/Sao_Paulo'

